### ISSUE TITLE
How i can get item on click  ??

### ISSUE THREAD

**Issue by mahmooddagga** [IntruderShanky/Sectioned-RecyclerView#2]
How i can get item on click  ??

**Comment by mahmooddagga** [comment]
or what the best form to get data from server  like this(section,item ) and fill in the adapter ?
please help?

**Comment by IntruderShanky** [comment]
you can get your item using sectionPosition or itemPosition

or you can create your own interface in adapter class

``` java
adapterRecycler.setOnItemClickListener(new SectionRecyclerViewAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int sectionPosition, int itemPosition) {
//sectionPosition is the position of section
//itemPosition is the position of item in that particular item.
                Log.d(sectionPosition + "", itemPosition + "");
            }
        });
```

**Comment by IntruderShanky** [comment]
Fetch data from server and add to the child Model or Section Model

**Comment by IntruderShanky** [comment]
Now in new update..
You can use click listner on view inside the adapter

**Comment by khurana3192** [comment]
When I click on an item, how can I get its section name?

**Comment by arsalanjibran** [comment]
can you provide onclick interface example
