### ISSUE TITLE
Click Lisner add delete

### ISSUE THREAD

**Issue by SumeshBalakrishnan** [IntruderShanky/Sectioned-RecyclerView#3]
hi, 
Thanks for this great work, and I need one more help that how we get on item click listner, ie,  like onsectionClicklistner I need two click event one for adding sub item, and one click listner for deleting the Header , pls help.

Thanks in advance...

**Comment by IntruderShanky** [comment]
Now issue solved 
Use:

``` java
insertNewSection(Section)
insertNewSection(Section, int)
removeSection(int)
insertNewChild(Object, int)
insertNewChild(Object, int, int)
removeChild(int, int)
```
