### ISSUE TITLE
is there easy way to perform sorting or filtering

### ISSUE THREAD

**Issue by mahmooddagga** [IntruderShanky/Sectioned-RecyclerView#4]

**Comment by IntruderShanky** [comment]
Use Comparable in your section class

**Comment by mahmooddagga** [comment]
i want to make filter on child not parent

**Comment by IntruderShanky** [comment]
@mahmooddaga
Yup.. you can do
Use comparable in you child class instead..

**Comment by mahmooddagga** [comment]
i don't have any idea to perform this , can you help please
